//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int IdCard { get; set; }
        public int IdClient { get; set; }
        public string CardNumber { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
